### ISSUE TITLE
Sample Program Improvements 

### ISSUE THREAD

**Issue by erictuvesson** [mellinoe/ImGui.NET#10]
I recently made [RenderContext](https://github.com/ChillyFlashER/OpenInput/blob/master/test/ImGuiNET/RenderContext.cs) it's based on the code from the sample program, however this might be easier to read / understand.

**Comment by mellinoe** [comment]
The sample program can certainly be cleaned up. I have much better versions of the boilerplate window loop stuff in other projects.

**Comment by mellinoe** [comment]
> Is there a reason the example didn't incorporate GameWindow from OpenTK and utilize the Run(); method from that implementation?

No important reason, really. I wasn't sure what OpenTK was doing under that abstraction and I'd rather just write out all the code that I needed, especially since it's example code.

> Is ImGui.NET caught up to handle font libraries like FontAwesome? Or is it still waiting on UTF8 support from your comment in #49

I'm not sure what you mean. ImGui.NET can load fonts itself using one of [these methods](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/IO.cs#L280-L302). It doesn't really integrate with other font libraries -- it manages fonts internally and draws its own text.

As for OpenTK.NETCore and OpenTK -- I don't have much involvement in it anymore. Personally, I don't use OpenTK in any of my projects anymore. It has long been on my to-do list to remove OpenTK entirely from this repository and replace it with [Veldrid](https://github.com/mellinoe/Veldrid). There are bugs in OpenTK and especially in my .NET Core port of it, as you've noticed.

**Comment by Huntk23** [comment]
> I'm not sure what you mean. ImGui.NET can load fonts itself using one of these methods. It doesn't really integrate with other font libraries -- it manages fonts internally and draws its own text.

Sorry, to clarify, I mean calling a glyph with the corresponding utf8 code in a string. I attempted and only got question marks.

> It has long been on my to-do list to remove OpenTK entirely from this repository and replace it with Veldrid. There are bugs in OpenTK and especially in my .NET Core port of it, as you've noticed.

I did not realize Veldrid was a replacement for OpenTK. Going to spend more time experimenting with that library then.

**Comment by mellinoe** [comment]
I've revamped the sample project entirely as of https://github.com/mellinoe/ImGui.NET/commit/ebb5fe2c6171db172612d1f7d65d6c747055c85b
