### ISSUE TITLE
Issues with Vector2 size.

### ISSUE THREAD

**Issue by Smilediver** [mellinoe/ImGui.NET#104]
I'm trying to get ImGui.NET working in Unity, but it turns out that in Unity System.Numerics.Vector2 is 16 bytes instead of expected 8, which causes misalignment issues in managed and native sides. It seems that this issue arises because Mono is treating Vector2/3/4 as 16 byte structs ready for SIMD optimizations. I know that you've already stated in #17 that you aren't planning on removing a dependency to System.Numerics, but with an issue like this, maybe you could reconsider your decision?

**Comment by mellinoe** [comment]
This was a known issue in Mono that should have been fixed for a while: https://github.com/mono/mono/issues/6411.

I know that Unity has historically been on a very old version of Mono, but the story should be different nowadays. Can you make sure that you are using the newer mono runtime, with [these settings](https://docs.unity3d.com/Manual/ScriptingRuntimeUpgrade.html)? I'm not sure if there is a way to tell which specific version is being used, or whether it includes the fix for the linked issue.

**Comment by Smilediver** [comment]
Ahh. I've found only the original bug report, and had the impression that Mono isn't going to fix it. Seeing that Mono actually fixed it, I'm off to bug Unity devs. :)

By the way, I've tried all the settings in Unity, that could potentially affect the size of Vector2, but nothing helps.
