### ISSUE TITLE
How to change font in monogame?

### ISSUE THREAD

**Issue by ejamshidiasl** [mellinoe/ImGui.NET#132]
Hello
this code is not working in monogame:
```
io.Fonts.AddFontFromFileTTF("GOTHIC.TTF", 22);
```
How to change font?

**Comment by soyemi** [comment]
Try this, it works for me.

Load font
```c#
ImGuiRenderer render;
//...
var font = ImGui.GetIO().Fonts.AddFontFromFileTTF(@"C:\Windows\Fonts\ARIAL.TTF", 13);
render.RecreateFontDeviceTexture();
```

Enable font on rendering
```c#
render.Update((float)deltaSec, inputs);
ImGui.PushFont(font);

ImGui.Text("It works");
```

**Comment by mellinoe** [comment]
@ejamshidiasl Were you able to try out the above?

**Comment by seemsindie** [comment]
@zcyemi This doesn't work in monogame sample since monogame ImGuiRenderer doesn't have the following methods `RecreateFontDeviceTexture()` and `Update(...)`

I am trying to just do this:

```
// In load
ImFontPtr font = ImGui.GetIO().Fonts.AddFontFromFileTTF("Roboto-Regular.ttf", 13);

// In draw
ImGui.PushFont(font);
ImGui.Text("Hello, world!");
ImGui.PopFont();
```

This doesn't work. The window just closes without any error. @mellinoe Any idea how to change font in monogame?

**Comment by Thraka** [comment]
This isn't working for me either

**Comment by Cuber01** [comment]
Hey guys, I figured it out.

The problem is in the sample XNA renderer.

``ImGuiRenderer.cs line 188:``

```csharp
ImGui.GetIO().Fonts.AddFontDefault();
```

You need to relpace it with:
```csharp
//ImGui.GetIO().Fonts.AddFontDefault();
ImGui.GetIO().Fonts.AddFontFromFileTTF("your/path", your_font_size);

```

I haven't figured out how to change it in code afterwards, but this is trivial as you can change it just fine using the demo window.

![image](https://user-images.githubusercontent.com/67684800/154833058-81651299-2487-4eb8-96ad-0aa5f2ca8d25.png)
![image](https://user-images.githubusercontent.com/67684800/154833303-edd0294f-81f6-4d0c-a3a1-efa08794009b.png)

**Comment by mellinoe** [comment]
@Cuber01 has the right idea. Note that there's very little Monogame-specific here in terms of loading the font up.

**Comment by kasperhbo** [comment]
> Hey guys, I figured it out.
> 
> The problem is in the sample XNA renderer.
> 
> `ImGuiRenderer.cs line 188:`
> 
> ```cs
> ImGui.GetIO().Fonts.AddFontDefault();
> ```
> 
> You need to relpace it with:
> 
> ```cs
> //ImGui.GetIO().Fonts.AddFontDefault();
> ImGui.GetIO().Fonts.AddFontFromFileTTF("your/path", your_font_size);
> ```
> 
> I haven't figured out how to change it in code afterwards, but this is trivial as you can change it just fine using the demo window.
> 
> ![image](https://user-images.githubusercontent.com/67684800/154833058-81651299-2487-4eb8-96ad-0aa5f2ca8d25.png) ![image](https://user-images.githubusercontent.com/67684800/154833303-edd0294f-81f6-4d0c-a3a1-efa08794009b.png)

Did you ever figure this out?
