### ISSUE TITLE
Where's the OpenTK example?

### ISSUE THREAD

**Issue by inputusernamehere** [mellinoe/ImGui.NET#136]
The readme claims there are OpenTK examples, but as far as I can tell there are none included in this project, and they are not linked to.

**Comment by dpethes** [comment]
Look in the commits from 2017/beginning of 2018, it's there somewhere. It was later replaced by Veldrid, I think.

**Comment by mellinoe** [comment]
Yeah, the OpenTK examples were stripped out, mainly because there occasional bugs caused by OpenTK itself (mostly related to windowing/input), and OpenTK wasn't receiving much development attention.

There has been some discussion on this topic before. I would be happy to support an OpenGL sample application if:
* It can build with the standard SDK tooling (e.g. `dotnet build`)
* It worked on Windows+macOS+Linux
* The dependencies are pulled down via NuGet
* [Ideally] It shared code with the other samples as much as possible

The last time this popped up, @giawa linked a branch of his which implemented a GL renderer: https://github.com/giawa/ImGui.NET/commit/43b2fc4e64e97a86c77cabe72926919cb5885157

That isn't using OpenTK, but you should get a pretty good idea of what the OpenGL calls look like from that branch.

**Comment by inputusernamehere** [comment]
I can't speak on behalf of OpenTK because I'm not involved with the development of it, but it's currently under active development and a 4.0 version is being prepared with .NET core support. I believe requirements 1-3 are met as of right now. Point 4 I wouldn't know about as I haven't been able to get imgui working with OpenTK myself yet. I'll take a look at the commit you linked though, thanks!

**Comment by NogginBops** [comment]
If anyone is still interested in a sample project of ImGui.NET working with OpenTK I have such a sample here 🙂:
https://github.com/NogginBops/ImGui.NET_OpenTK_Sample

**Comment by enquel** [comment]
@NogginBops thank you. Works like a charm. I am happy with Veldrid for now, but in case I need this, it will be a time saver.

**Comment by oohicksyoo** [comment]
@NogginBops Thanks for the sample really helped in setting up my implementation for my engine that is using OpenGL and SDL2

**Comment by shayded-exe** [comment]
Sorry to revive an old thread, but now that Veldrid is no longer receiving updates, it would be great for this to be revisited. Also, what about Silk.Net?

**Comment by NogginBops** [comment]
@shayded-exe see my comment for an OpenTK implementation. 

For silk I would recommend opening a separate issue, but I do think they provide an implementation but I don't know the details.
