### ISSUE TITLE
Did it support OGL330?

### ISSUE THREAD

**Issue by MikiraSora** [mellinoe/ImGui.NET#15]
![svl7 vara7vru fhyciyxwq](https://cloud.githubusercontent.com/assets/7549173/25335562/243126ce-2926-11e7-93b4-97cba16009e6.png)
there is nothing.
![xt il sr6ipr9 4 z jl7c](https://cloud.githubusercontent.com/assets/7549173/25335564/277c3e2c-2926-11e7-943d-bbc9a2044ba9.png)

is ImGUI still use OpenGL Immediatly mode for rendering ?

**Comment by mellinoe** [comment]
Hey @MikiraSora , a couple things:

1) ImGui.NET doesn't actually render anything itself. It just gives a bunch of textured triangles to your application, and it's up to you to render them in whatever way is most convenient. 

2)The sample program is just there as a demonstration of how it works, but I wouldn't recommend using the code directly in your application, primarily because it uses fixed-function OpenGL. We could add another sample program that uses Direct3D, or OpenGL 3.3+. There are a bunch of other sample programs on https://github.com/ocornut/imgui that could be converted, such as [this OpenGL 3 example](https://github.com/ocornut/imgui/tree/master/examples/opengl3_example). I'm not planning to do this myself anytime soon, but would review a PR for it.

**Comment by MikiraSora** [comment]
It's so cool ! That's IMGUI.Net just provide a set of verteices and colors by its "rendering function" and I have to draw them? I learn it,Thx :D

**Comment by mellinoe** [comment]
@MikiraSora Yep, that's exactly right. The library is designed to be embedded into a separate rendering engine so it tries to be as simple as possible.
