### ISSUE TITLE
Font's returned as garbage 

### ISSUE THREAD

**Issue by dmitsuki** [mellinoe/ImGui.NET#24]
I'm not getting back the default font correctly. I'm receiving it as garbage. Only portions of the first two lines are read, and nothing else is returned properly 

IO io = ImGui.GetIO();

            FontTextureData textureData = io.FontAtlas.GetTexDataAsRGBA32();
int[] pixels = new int[textureData.Width * textureData.Height];
            int count = 0;
            for (int i = 0; i < textureData.Height; i++)
            {
                for (int j = 0; j < textureData.Width; j++)
                {
                    
                    pixels[i + j] = *((uint* )textureData.Pixels + count);
                    count += textureData.BytesPerPixel; 
                }
            }

Is an example of how I'm getting the data. It seems to read the only the first two lines, then it returns transparent pixels for the rest. 

If I load the font texture myself (as a png I took from the native imgui) everything works fine.

**Comment by mellinoe** [comment]
On my phone so I can't look too closely. I'm pretty sure that the problem is that you are indexing your pixels array incorrectly, though. You should be using "j + (i * width)" as your index. It makes sense that you are only filling in the first two rows with your current code, although it should all be garbage data.



On Jun 15, 2017, at 7:06 PM, dmitsuki <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not getting back the default font correctly. I'm receiving it as garbage. Only portions of the first two lines are read, and nothing else is returned properly

IO io = ImGui.GetIO();

        FontTextureData textureData = io.FontAtlas.GetTexDataAsRGBA32();


int[] pixels = new int[textureData.Width * textureData.Height];
int count = 0;
for (int i = 0; i < textureData.Height; i++)
{
for (int j = 0; j < textureData.Width; j++)
{

                pixels[i + j] = *((uint* )textureData.Pixels + count);
                count += textureData.BytesPerPixel;
            }
        }


Is an example of how I'm getting the data. It seems to read the only the first two lines, then it returns transparent pixels for the rest.

If I load the font texture myself (as a png I took from the native imgui) everything works fine.

**Comment by dmitsuki** [comment]
DOH! 

I have been staring at this for so long my brain was automatically turning "i+j" into the definition of a multidimensional array or something, but the computer correctly assumes it's just arithmetic. 

I'm somewhat curious as to how the first two lines always came out correctly but that's enough of that for now. Sorry for that.
