### ISSUE TITLE
Random crashes that are impossible to debug due to missing Exception throwing

### ISSUE THREAD

**Issue by julcreutz** [mellinoe/ImGui.NET#251]
I'm using ImGUI for an in-game editor for my game. Particles, Entities, Tiles, Maps etc.

Sadly, the game crashes randomly upon events in ImGUI. This can just be activating the editor, clicking something etc.

**The game silently crashes, without an exception being thrown.**

This is driving me nuts. Is there any way I could debug this?

The error code is always just a random number. Usually very large, sometimes it's 1.

EDIT: This may be helpful: the windows crash log says something about "StackHash_a99c".

**Comment by ossyahya60** [comment]
Hi, I have exactly the same issue, I get random exception, access violations and etc...
They all happen randomly like clicking on a ImGui element and etc, if you found a solution to this, please let me know.

Side Question: do you how to make ImageButton? it requires a 'texture_id' which is intptr, do you know how to get that id?

**Comment by julcreutz** [comment]
> Hi, I have exactly the same issue, I get random exceptions, access violations and etc...
> They all happen randomly like clicking on an ImGui element and etc, if you found a solution to this, please let me know.

Damn, sorry to hear you're also suffering from this issue.

**Comment by julcreutz** [comment]
Hey, so I've analyzed a few crash dumps of mine and found something.

I'm not an expert, but I suppose the most notable lines are these right here:

cimgui!igValueInt+0x1f279

ntdll!RtlFreeHeap+0x51
I've appended the full crash dump analysis.

windbg_crashdump_analysis.txt

**Comment by ossyahya60** [comment]
Can you tell me how you managed to make this analysis? 
Thank you BTW XD

**Comment by julcreutz** [comment]
I did it using WinDbg. You can download it.

I then opened the generated crash dump file and analyzed it using '!analyze -v'.

**Comment by ossyahya60** [comment]
@julcreutz Hi, did you found a solution to this problem?

**Comment by bootzin** [comment]
It's very hard to know the exact cause of this problem without some sample code to reproduce the issue.
Try making a very simple example where the same problem happens, it's usually easier to debug, and you'll probably find out the source of the issue in the process.

Here are my guess as to what is happening, but as I said, it's just a guess:
The crash is happening because an error is occurring within imgui itself. This means that, for some reason, there is an error being thrown in the native library. As native code is unmanaged, the IDE has no way of knowing the precise cause of the error, it simply knows that something went wrong. Depending on the severity of the error, this may lead to an access violation or a complete sudden crash.

Imgui itself is most likely not causing the issue, so you've either setup something incorrectly, or you're passing the wrong data to an imgui call. My suggestion is that you double check the places where you make such calls to make sure that the method is being called correctly. Pay extra attention to places where parameters are passed in as ref or as structs. 

If you have a lot of places where you use imgui, try identifying a pattern in the crash. They're probably not random, so try to reproduce them and find out what is causing the issue. Is it during drag and drop? Is it with an array? Maybe after some time? Even if you don't find the pattern, think back as to what were you doing when it crashed. If you were pressing a button, investigate that button call, maybe even search in [imgui source code](https://github.com/ocornut/imgui/blob/master/imgui.cpp) to see what else is called from within that function. In the button example, maybe it is crashing because the mouse click is incorrectly configured?

Anyway, as I still lack divination powers, I cannot figure this out for you, but I'm sure that with the instructions I've provided you'll be able to find the cause of the problem. Good luck!

**Comment by julcreutz** [comment]
> @julcreutz Hi, did you found a solution to this problem?



> It's very hard to know the exact cause of this problem without some sample code to reproduce the issue.
> Try making a very simple example where the same problem happens, it's usually easier to debug, and you'll probably find out the source of the issue in the process.
> 
> Here are my guess as to what is happening, but as I said, it's just a guess:
> The crash is happening because an error is occurring within imgui itself. This means that, for some reason, there is an error being thrown in the native library. As native code is unmanaged, the IDE has no way of knowing the precise cause of the error, it simply knows that something went wrong. Depending on the severity of the error, this may lead to an access violation or a complete sudden crash.
> 
> Imgui itself is most likely not causing the issue, so you've either setup something incorrectly, or you're passing the wrong data to an imgui call. My suggestion is that you double check the places where you make such calls to make sure that the method is being called correctly. Pay extra attention to places where parameters are passed in as ref or as structs.
> 
> If you have a lot of places where you use imgui, try identifying a pattern in the crash. They're probably not random, so try to reproduce them and find out what is causing the issue. Is it during drag and drop? Is it with an array? Maybe after some time? Even if you don't find the pattern, think back as to what were you doing when it crashed. If you were pressing a button, investigate that button call, maybe even search in [imgui source code](https://github.com/ocornut/imgui/blob/master/imgui.cpp) to see what else is called from within that function. In the button example, maybe it is crashing because the mouse click is incorrectly configured?
> 
> Anyway, as I still lack divination powers, I cannot figure this out for you, but I'm sure that with the instructions I've provided you'll be able to find the cause of the problem. Good luck!

Hey, you two!

Yes, I FINALLY did the fix the issue.

What I basically did is recompile cimgui with exceptions turned ON and in DEBUG mode. Funnily enough, cimgui is compiled without exception throwing, that's why it crashes silently.

After using my custom built .dll, my game crashed with an assertion being thrown. Through that, I could fix the issues. It was mostly mismatches between TreeNode/BeginChild/PushID and TreePop/EndChild/PopID calls.

**Comment by ossyahya60** [comment]
That's Fantastic!, Can you please tell me the exact steps you did?
(How you did recompiling)

**Comment by julcreutz** [comment]
> That's Fantastic!, Can you please tell me the exact steps you did?
> (How you did recompiling)

Sure! I'm not a C++ dev so this was very new for me too.

This is the repo you need: https://github.com/mellinoe/ImGui.NET-nativebuild.
You need to clone it **recursively**.

You then need to change the **Makefile** in the cimgui folder and change 
`"CXXFLAGS=-O2 -fno-exceptions -fno-rtti"`
to
`"CXXFLAGS=-O2"`

You also need g++ and make. I installed them with choco, a package manager for windows.

Then just run
`make all`
in the cimgui folder and it should generate the correct cimgui.dll.

Appended is the compiled .dll if you don't want to go through all these steps, but I encourage you to do so.

Good luck!

[cimgui.zip](https://github.com/mellinoe/ImGui.NET/files/6394035/cimgui.zip)

**Comment by ossyahya60** [comment]
Thank you!, well this work if I have ImGui v1.78 (Nuget Package)?

**Comment by zaafar** [comment]
@ossyahya60 @julcreutz It sounds like a good step-by-step guide to put in the readme under the heading "how to enable imgui exceptions and run it in the debug mode". :)

**Comment by ossyahya60** [comment]
I think this is a good idea.

**Comment by mellinoe** [comment]
I added some instructions in the README, since this is a common pain point: https://github.com/mellinoe/ImGui.NET/blob/master/README.md#debugging-native-code
