### ISSUE TITLE
Long input fields?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#255]
I just realized there doesn't seem to be a way to make long gui field without losing info due to everything taking a int.
Can we have a long version?

**Comment by mellinoe** [comment]
I believe what you want is to use the "Scalar" functions, e.g. `ImGui.DragScalar` and `ImGui.InputScalar`, with an appropriate ImGuiDataType value, e.g. `ImGuiDataType.S64` for a 64-bit signed integer. These functions are a bit unintuitive in their wrapped form, because you need to use unsafe code to provide the pointer to the data you are manipulating, instead of a safe ref. Something like:

```C#
long x = long.MaxValue;
if (ImGui.DragScalar("Test", ImGuiDataType.S64, (IntPtr)(&x), 1.0f)
{
    // Value changed
}
```

Does that work for you?

**Comment by Shadowblitz16** [comment]
I can check it out, but It would be nicer to have a more managed version.

**Comment by mellinoe** [comment]
For this kind of thing, I'd prefer not to add extra non-wrapper functions to ImGui.NET. Instead, I'd suggest you add this kind of helper function to your own project:

```C#
public static unsafe bool DragInt64(string label, ref long value, float speed)
{
    fixed (long* valPtr = &value)
    {
        return ImGui.DragScalar(label, ImGuiDataType.S64, (IntPtr)valPtr, speed);
    }
}
```

It can be pretty easily adapted to the other possible values of `ImGuiDataType` as needed.

**Comment by Shadowblitz16** [comment]
ok thankyou so much

**Comment by Shadowblitz16** [comment]
@mellinoe whats the best way to do string and chars too?
