### ISSUE TITLE
Is there a way to use this with SDL-CS?

### ISSUE THREAD

**Issue by DoogeJ** [mellinoe/ImGui.NET#322]
I'm using https://github.com/flibitijibibo/SDL2-CS in a C# project and would love to use ImGui to implement debugging GUIs

**Comment by mellinoe** [comment]
Yep, it should be possible. Take a look at [this example project](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_sdlrenderer.cpp) in the dear imgui repo. You'd have to translate this to C#, but presumably SDL2-CS is a very close mapping to the native library so it should be relatively straightforward. Note that even if you're using SDL2, you will usually be using another graphics library on top of it (e.g. D3D, Vulkan, OpenGL, etc.). If that's the case for you then you'd be better off using a renderer built on that graphics API since it will fit in with the rest of your code much better.

I'll close this out, but if someone is sufficiently motivated then they could submit an SDL2 renderer written in C# to the repo here as a reference for others.

**Comment by GaryHuan9** [comment]
Hello, I am currently using ImGui.NET and SDL-CS in my project. It uses the SDL Platform and Renderer as a Dear ImGui backend. You can checkout the main integration implementation here: https://github.com/GaryHuan9/Echo/blob/c816c3ec4017a817ce23906b8029019cb5d8772e/Echo.UserInterface/src/Backend/ImGuiDevice.cs
