### ISSUE TITLE
Assertion failed when using custom cimgui build

### ISSUE THREAD

**Issue by iocmet** [mellinoe/ImGui.NET#328]
![image](https://user-images.githubusercontent.com/63492966/172273522-2b51688c-22ee-4a7a-87db-34bfdf9d916b.png)
my build steps

git clone https://github.com/cimgui/cimgui
cd cimgui
git clone https://github.com/ocornut/imgui
mingw32-make

**Comment by sonoro1234** [comment]
There could be alot of different issues, but at first glance: cimgui must be in sync with a specific imgui commit so that when cloning or pulling it recursive must be used: https://github.com/cimgui/cimgui#compilation unless you do generation yourself.

**Comment by mellinoe** [comment]
If you have literally just built a different version of cimgui.dll and dropped it into the repository here, there's a very high chance that won't work. You need to go in and re-run the native binding generator using the metadata files that correspond to the exact version of cimgui that you're using. This is because the layout of the native library (it's structures, functions, etc.) have probably changed in a way that is incompatible with the version that you've switched to.
