### ISSUE TITLE
OpenTK + SDL2 issues on Windows

### ISSUE THREAD

**Issue by dpethes** [mellinoe/ImGui.NET#34]
I had encountered this most bizzare issue: I couldn't get the sample program running when I returned to imgui.net after some time; even the older builds didn't work. Long story short - I figured out that after setting _nativeWindow.Visible = true; it was still false, so it wouldn't enter the eventloop and just close right away.  It only happens when SDL2 is in the library load path - the GraphicsContext creates an internal context of type {OpenTK.Platform.Windows.WinGLContext}, but when it can find SDL2, it creates a context of type {OpenTK.Platform.SDL2.Sdl2GraphicsContext}, which exhibits the issue. So it probably has some bug, or needs some additional setup in this case. 
It happens both with OpenTK for .net core and regular OpenTK2, on Windows 7/10, various SDL2 versions.

**Comment by mellinoe** [comment]
Hmm. I've experienced many weird quirks like this with OpenTK in the past, so much that I've stopped using it for my other projects. It could be worth investigating, but it could also be worth it to rip out OpenTK altogether.

**Comment by dpethes** [comment]
Any suggestions for alternatives?

**Comment by njankowski** [comment]
One option may be to eschew OpenTK for anything but its OpenGL bindings.

SDL2 could be used for windowing, context creation, and input.
[SDL2-CS](https://github.com/flibitijibibo/SDL2-CS) is a terrific .NET binding for SDL2.

Create the OpenGL context with SDL2 and initialize OpenTK with that context.

For example:
`
IntPtr sdlGLContext = SDL_GL_CreateContext(sdlWindow);
`
`
GraphicsContext openTKGraphicsContext = new GraphicsContext(new ContextHandle(sdlGLContext), (proc) => SDL_GL_GetProcAddress(proc), () => new ContextHandle(SDL_GL_GetCurrentContext()));
`

Note that some SDL2 code would be needed prior to this, error checking is missing, and I did not set any attributes for the context.

This initializes OpenTK for use with an externally managed context.
It takes the context and a couple of callbacks as arguments.

At this point, GL calls should work, but SDL2 must be used to swap the window and destroy the context, since OpenTK does not own the context.

I have been using this method and it has worked without problems so far.

**Comment by dpethes** [comment]
@njankowski  Thanks very much for the advice!

**Comment by mellinoe** [comment]
That's definitely an option. I took that route for a while (using my own SDL2 bindings), although I've since stopped using OpenTK for the GL bindings (rolled my own minimal set as well).

There's a couple really simple fixes, though, which don't require changing much.

1. Add this line before creating the window:

`Toolkit.Init(new ToolkitOptions() { Backend = PlatformBackend.PreferNative });`

It just forces OpenTK to use the native backend, which doesn't have this problem. This is kind of hacky, though. It's probably better to instead:

2. Replace this line:
`while (_nativeWindow.Visible)`
with
`while (_nativeWIndow.Exists)`

I just pushed https://github.com/mellinoe/ImGui.NET/commit/17f05b9492e5dce68f7107814ac8ca1b207a52bd with that change.

I'll leave this issue open because I do want to replace this dependency in the sample code.

**Comment by dpethes** [comment]
@mellinoe both methods work, but it looks like there's another bug in the SDL2 backend (method 2) - the mouse coordinates are offset by random values (each time the program is run, the offset is different), which makes interacting with the gui impossible. This looks like an issue in OpenTK for .net core, regular OpenTK2 works.

**Comment by mellinoe** [comment]
I've removed all uses of OpenTK in the sample code here. If there are any issues with the Veldrid libraries that have replaced it, then I am very interested in fixing them.
