### ISSUE TITLE
Use image with Monogame

### ISSUE THREAD

**Issue by Catvert** [mellinoe/ImGui.NET#36]
Hi, I'm using Monogame with ImGUI and I can't find a way to display an image (e. g. ImageButton) with ImGUI from a Texture2D. Thanks for your help.

I use this wrapper : https://github.com/procfxgen/ImGuiMG/blob/master/Game1/ImGuiMg.cs

**Comment by mellinoe** [comment]
The [`IntPtr userTextureID` parameter](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/ImGui.cs#L132) is what ImGui uses to let track which texture was used for a button.

When you get the draw list back, each draw item has a texture ID associated with it. Usually what you will do is have some sort of map from IntPtr (ImGui ID) -> Texture2D (MonoGame object). Then, when you get the ID in a drawlist, you can use your map to bind the appropriate texture object. Currently, the code you linked has an array of textures, and it binds one of them before drawing, but there's a bit more that needs to be done. https://github.com/procfxgen/ImGuiMG/blob/master/Game1/ImGuiMg.cs#L364

I use this utility class which you could reference. It uses my graphics library rather than MonoGame's, but it should be simple to translate across.

https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiImageHelper.cs

You first call [GetOrCreateImGuiBinding](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiImageHelper.cs#L42) to get the IntPtr to pass into ImGui.ImageButton. Then, when rendering, you call [GetShaderTextureBinding](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiImageHelper.cs#L59) to get your Texture2D back. It uses a static dictionary to track the mappings.

**Comment by Catvert** [comment]
Thank you for your answer, your solution works perfectly!

**Comment by mellinoe** [comment]
@Catvert Glad to hear that. Cheers!

**Comment by mjkkirschner** [comment]
I can no longer find ` GetShaderTextureBinding` and it seems that `GetImageResourceSet()` doesn't return anything useful besides `Name`. Is there a method I am missing to retrieve the texture from the binding id?

**Comment by mellinoe** [comment]
@mjkkirschner There's no function to get a `Texture` back from a binding ID, but I don't think it should be necessary. The binding ID's only track Textures that you have given to it. The recommended way to use it is to never store the IntPtr's that it returns, and to just pass those directly through to `Image`/`ImageButton`.

Feel free to file a new issue if something is unclear about the usage -- discussions are likely to get lost in an old issue like this.
