### ISSUE TITLE
Analogue of this colors from imgui 1.51 in 1.89.1?

### ISSUE THREAD

**Issue by iocmet** [mellinoe/ImGui.NET#368]
~~ImGuiCol.ComboBg~~ ImGuiCol.PopupBg
ImGuiCol.CloseButton
ImGuiCol.CloseButtonHovered
ImGuiCol.CloseButtonActive

**Comment by mellinoe** [comment]
I can't do much to change how this behaves since this is just a thin wrapper over the native library. I'd suggest you write some small helper functions that push/pop the regular button colors for your specific use case. It won't be quite as easy as setting the colors once, but I believe it should work fine.
