### ISSUE TITLE
ImGui bug in ImGui::RenderDimmedBackgroundBehindWindow

### ISSUE THREAD

**Issue by iocmet** [mellinoe/ImGui.NET#371]
This line is adding an empty draw cmd
```draw_list->AddDrawCmd();```
and ElemCount is 0 so it causes crash and in this line
```draw_list->PushClipRect(viewport_rect.Min - ImVec2(1, 1), viewport_rect.Max + ImVec2(1, 1), false);```
first two args must be 
```viewport_rect.Min + ImVec2(1, 1), viewport_rect.Max - ImVec2(1, 1)```
because it causes crash too because like if rect min and max is 0 0 and 1920 1016 it will try push clip rect with (-1, -1) (1921, 1017) so it will cause crash because it outside of window

Sorry i can't create issue on imgui github "You cannot perform this action" so i creating it here

**Comment by mellinoe** [comment]
Unless this problem was introduced specifically by the C# bindings, there is not much I can do to fix this. In fact, this function doesn't even seem to be part of the public API and isn't exposed by ImGui.NET normally (it's an implementation detail and not even available in imgui.h). Based on that, and the details of your error, I suspect the function is only designed to be called in specific places by the implementation itself. Feel free to reopen if I'm missing something, but I don't think there's much I can do here.
