### ISSUE TITLE
Shared project setup

### ISSUE THREAD

**Issue by xposure** [mellinoe/ImGui.NET#47]
Thoughts on moving to a shared project setup so that we can create bindings for different targets (like monogame for example)?

This would also help with this issue here https://github.com/mellinoe/ImGui.NET/issues/17

**Comment by mellinoe** [comment]
By "different targets", I guess you're referring to different target frameworks (e.g. .NET 4.0, .NET 4.5, etc)? There shouldn't be anything stopping you from using the project as-is in MonoGame, unless you're targeting a very old version of .NET. I know that @jjagg has used the project in MonoGame, and he has code snippets around somewhere. I'm not sure if he's using the NuGet package or re-building the binaries himself, but in principle there's no real difference.

For the main project itself, I'm not really interested in supporting anything other than .NET Standard. IMO there is no legitimate reason to in an environment that doesn't support it at this point.

**Comment by xposure** [comment]
A shared project is too easy to use and absolutely zero hassle to maintain in a project like this. It would easily solve the System.Numeric I linked and allow you to easily push out nugets for other frameworks with almost no effort allowing people to simply call a few functions instead of copy and pasting boilerplate code in to their project. 


Base branch, I left my IFDEFs in there and also copied the ArrayPool code from corefx straight in to the project to drop the buffer dep which is also in another issue here somewhere.

 https://github.com/xposure/ImGui.NET/tree/sharedproj

Here is a branch using the sharedproj to create a MonoGame dep which means all the vector2/3/4 will be correctly typed so people don't have to build this project and can use the nuget package (like I tried to).

https://github.com/xposure/ImGui.NET/tree/monogame

**Comment by mellinoe** [comment]
It's not a huge burden, but I don't think adding extra projects (some of which use legacy project syntax and require manual maintenance), extra configurations, and lots of #if's is "zero hassle". It's still something that I need to manage, test, and keep on top of for every release. I don't use MonoGame, so now I also have the burden of testing a configuration for a product I don't use. That means I probably need to install an SDK, familiarize myself with it, and add extra testing time whenever I add a feature.

Stepping back, the real reason this is necessary is because of different vector types. How feasible is it for MonoGame to provide implicit conversions to/from the BCL vectors? If those were in place, you could just use MonoGame vectors and everything would work fine. There are a lot of libraries in the ecosystem nowadays that are using the BCL vectors, so I think adding these conversions would help MonoGame users in general, not just with ImGui.NET. I do acknowledge that it would be frustrating to use ImGui without a way to unify the vector types.

**Comment by xposure** [comment]
Yep and the first thing I thought of was to instead clone MonoGame and convert it to use System.Numerics instead of its own. Even past the the idea of unifying to the BCL there are other advantages with using System.Numerics like SIMD. Its just when I look at how hard that would be to maintain compared to this, its quite the task.

I also agree about the IFDEFs, but I figured that was on the table as it was mentioned by you in the issue I linked. Do you have any other ideas that I could investigate? I would be more than happy to look in to other solutions if you have some ideas.

**Comment by mellinoe** [comment]
> Its just when I look at how hard that would be to maintain compared to this, its quite the task.

Adding the implicit conversions, though, should just be two lines of code and maybe some build configuration work (I dunno how MonoGame build configurations are done). And it would help with a lot of other libraries in the ecosystem. Like if you want to use ImageSharp, for example, you'd also need to convert back and forth between MonoGame/system vectors. It wouldn't be as painful probably, because their API doesn't take a vector in every single method like ImGui tends to.

**Comment by xposure** [comment]
@Jjagg yea its not hard to get up and running, you can see it in the monogame branch under ImGuiHelper that I linked above (code is just BOTA).

Also I agree about moving forward. Correct me if I'm wrong but I have the following options here.

1. Look in to getting MonoGame to providing an implicit cast. Which really isn't that much work, but getting the PR accepted might be (and waiting for the long release cycle so I might as well go as a submodule).

2. Do my own conversion to and from MonoGame vector and numerics (perhaps a simple extension but that just feels clunky).

3. I could fork this project and add monogame to imgui and change all the references. I use monogame portable for cross platform development which can't be used in a .net standard 1.1 project. So I would have to change the project type as well here.


@mellinoe Implicit casting could be hidden performance costs. I'm not sure how well the JIT can optimize those out if at all possible. In this case it might not be that big of a deal since you aren't implicitly casting a large amount of data.

I've been toying with the idea of making and editor and have been closely watching the docking issues over at imgui. I seen recently that you added some of this in to imgui.net, this is what brought me back around to the project.



With that being said. When discussing things like being more .NET friendly as in issue 1, this really doesn't seem to be the case. There are a lot of loose ends with function definition not aligning to the core imgui and people being forced to use unsafe code which could be a hurdle for some people.

**Comment by mellinoe** [comment]
> @mellinoe Implicit casting could be hidden performance costs. I'm not sure how well the JIT can optimize those out if at all possible. In this case it might not be that big of a deal since you aren't implicitly casting a large amount of data.

There shouldn't be any cost, it's not actually doing any conversion. It's just reinterpreting the pointer as a managed reference, and trusting that the data is valid (so we're trusting the native code to be correct w.r.t. its size and bounds).

**Comment by xposure** [comment]
Putting this here for some reference https://github.com/MonoGame/MonoGame/issues/3781

**Comment by dpethes** [comment]
Fwiw, a very convenient way to use the bindings is just to take all the source files and join them to single source file (like [Petapoco](https://github.com/CollaboratingPlatypus/PetaPoco) does, for example). Then just drop it inside any project as needed. It's a bit more work when updating to new versions, but compatibility changes take more time anyway.

**Comment by xposure** [comment]
@mellinoe Is there any concern with someone else maintaining a different port following your name convention on nuget `ImGuiNet.MonoGame` or would you want it named differently so they don't appear as the same?

**Comment by mellinoe** [comment]
@xposure I'd prefer that they used a different prefix (e.g. `MonoGame.ImGuiNET`), but I'm not opposed to it in general. As long as it was clear that the library is a third-party extension (and people don't come looking here for support 😀) then it should be fine.

**Comment by tlgkccampbell** [comment]
@mellinoe I'm experimenting with incorporating ImGui.NET into my own (non-MonoGame) rendering framework and decided to take your advice with respect to implicit vector casts. Unfortunately, it seems like a straightforward "reinterpret cast" fails under some circumstances when using the Numerics types.

Consider the following struct:

```csharp
public struct Vector2 { public Single X; public Single Y; }
```
Consider also the following unit test:

```csharp
public void Vector2_ConvertsFromSystemNumericsCorrectly()
{
    var vector1 = new System.Numerics.Vector2(1.2f, 3.4f);
    Vector2 vector2 = vector1;

    Assert.AreEqual(vector1.X, vector2.X);
    Assert.AreEqual(vector1.Y, vector2.Y);
}
```

That test will fail when run as 64-bit in the Release configuration using either of the following implementations of an implicit conversion operator, because the converted vector appears to be full of garbage data:

```csharp
public static unsafe implicit operator Vector2(System.Numerics.Vector2 value) =>
    *(Vector2*)&value;

// OR

public static unsafe implicit operator Vector2(System.Numerics.Vector2 value) =>
    Unsafe.As<System.Numerics.Vector2, Vector2>(ref value);
```

For reasons that I don't fully understand, the following implementation works:

```csharp
public static unsafe implicit operator Vector2(System.Numerics.Vector2 value)
{
    var x = (Vector2*)&value;
    return *x;
}
```

This example is illustrative of a larger problem; other vector types produce similar issues, going in both directions. Considering the number of runtimes and platforms I support at this point, the whole thing is making me more nervous the more I delve into it.

**Comment by tlgkccampbell** [comment]
It looks like you're correct; the bug doesn't reproduce under .NET Core 2.1 or Mono, only under the CLR. I can observe a minor difference in the assembly output, and setting COMPLUS_FeatureSIMD=0 does indeed fix the issue. I'll file an issue on coreclr.

**Comment by tlgkccampbell** [comment]
Apparently the difference here was a result of the fact that .NET Framework 4.7.2 is on an older version of RyuJIT than .NET Core 2.0. Installing the .NET Framework 4.8 Preview eliminates the issue.

**Comment by mellinoe** [comment]
I'm happy with the current structure of the library, and there is now an example renderer for MonoGame/FNA included in the repo. I'm happy to merge in more samples to demonstrate integrations with additional common graphics libraries.
