### ISSUE TITLE
FNA renderer & sample program

### ISSUE THREAD

**Issue by flyingpie** [mellinoe/ImGui.NET#60]
So I'm backporting the FNA renderer from https://github.com/0x0ade/ImGuiCS to ImGui.NET, with as few changes to ImGui.NET itself.

I was wondering if there's an interest to merge that into this repo when it's done, and maybe other types of renderers and sample programs.

Kudo's to what you're doing here and with Veldrid, these are some awesome libraries!

For reference, here's the WIP: https://github.com/FlyingPie/ImGui.NET/tree/fna

**Comment by mellinoe** [comment]
I'd be happy to merge additional renderers in, especially ones for common graphics libs and frameworks. It would be nice if the setup and rendering code was isolated somehow, and the rest of the generic demo code was shared between them all. It would help demonstrate what you actually need to implement to render the library's output, and what is portable.

As for changes to ImGui.NET itself: we should probably hold off on anything there. In the near future, I am going to rework a large portion of the code so that it is auto-generated from the [automatic C bindings](https://github.com/ocornut/imgui/issues/1879) that are being worked on. Once I figure out what that looks like, we can make incremental improvements to it. Changes made in the meantime will probably get overridden by the work there.

At the same time, the small additions you've made to IO.cs are totally fine. I don't see a reason we couldn't merge those in.

**Comment by FlyingPie** [comment]
Thank you for your comment, I look forward to the automatic generation bits, should save lots of work when updating ImGui.

As for the part about isolating renderers, I can see that being very helpful for clearity. The renderers as they are now seem somewhat messy to me, magically gluing different components together.

What are your thoughts on some kind of interface and a few simple classes or structs to make a clear layer between ImGui and the implementing renderers? Stuff like "load and bind this texture", "rebuild font atlas" and "draw these vertices using these indices". I feel that the renderers all have the same kind of structure, with just library/framework specific differences. Maybe introducing a bit of shared "contract" could make them pluggable so the demo code can be shared as well.

**Comment by mellinoe** [comment]
> What are your thoughts on some kind of interface and a few simple classes or structs to make a clear layer between ImGui and the implementing renderers?

I think that's a good idea, and would help the usability even further. There's a few things that could be standardized, I think:

* Initializing general device resources (e.g. shaders, buffers, etc.)
* Initializing / re-initializing the font texture
* "Registering" a user image (for `ImGui.Image`) and potentially "un-registering" them.
* Handle drawing the command list

We could try to formalize that after we add an FNA renderer, and potentially I could revive and/or rewrite the raw OpenGL version as another example.

**Comment by flyingpie** [comment]
The "FNA renderer and sample program" part of this issue are done, closing.
