### ISSUE TITLE
Click events are sometimes eaten.

### ISSUE THREAD

**Issue by zhengying** [mellinoe/ImGui.NET#63]
Click events are sometimes eaten. 
eg:  fast click a button 10 times, at least 3 times no response

I test the native imGui version 1.53(the same version as imGUI.NET), no this problem.

this is compare gif

Native imGUI:
![imgui_opengl3-export](https://user-images.githubusercontent.com/1042545/44449025-8c217500-a61f-11e8-904e-af6aa84c82ab.gif)

ImGUI.NET: 
![imgui net-export](https://user-images.githubusercontent.com/1042545/44449027-8c217500-a61f-11e8-85a6-0953653f92ce.gif)

----
environment：
macOS 10.12.6
ImGui.NET with metal Backend, opengl Backend

**Comment by mellinoe** [comment]
This is probably because of the way mouse events are passed through to ImGui here: https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs#L330. This will miss mouse clicks that are pressed and released in the same frame. Something like this should be done:

https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_sdl.cpp#L213

**Comment by mellinoe** [comment]
I pushed a small fix that basically does what the linked C++ code does. It should catch any mouse presses that are started since the last from, and not only ones that are still held.
