### ISSUE TITLE
Blurry Text in Monogame when using DirectX (with fix)

### ISSUE THREAD

**Issue by roy-t** [mellinoe/ImGui.NET#97]
In the MonoGame sample all the vertices are offset by 0.5 pixel, this causes everything to be slightly blurry. This was especially noticable when rendering text. I've tested this using the DirectX version of monogame, but it might be the case that this fix should not be applied with the OpenGL variant. (I couldn't test it yet).

Blurry:
![text_a](https://user-images.githubusercontent.com/623634/50595661-a149c280-0ea1-11e9-9635-2fa870f0e697.PNG)

Not blurry:
![text_c](https://user-images.githubusercontent.com/623634/50595665-a3138600-0ea1-11e9-8d52-9d8d883a9592.PNG)

The fix was to remove the special offset here and render it just like FNA would: 
https://github.com/mellinoe/ImGui.NET/blob/4c9e1579b66e0cdccebcf3dd6f27ad7ff07524a6/src/ImGui.NET.SampleProgram.XNA/ImGuiRenderer.cs#L199

**Comment by mellinoe** [comment]
Interesting -- the example as written works fine for the OpenGL renderer. What is the general pattern for dealing with backend-specific rendering differences in MonoGame?

**Comment by roy-t** [comment]
Hmm, the reason for the 0.5f (half-pixel) offset was because DirectX 9 interprets (0, 0) as the top left corner of the top left pixel. So to avoid interpolation you had to offset everything by half a pixel so that you're drawing at the center of the top left pixel. XNA targetted DirectX 9 (though required DirectX 10 to make sure some features were available in the GPU).  But MonoGame targets DirectX 11, in which (0, 0) is the center of the top left pixel. So this offset is no longer needed.

To be honest I do not have a clue why the code is necessary for the OpenGL renderer. This problem should have never existed there. Is the text blurry under the OpenGL renderer if you remove the half-pixel offset?

**Comment by mellinoe** [comment]
> Is the text blurry under the OpenGL renderer if you remove the half-pixel offset?

Yes, it looks quite bad:

![image](https://user-images.githubusercontent.com/8918977/50622249-95b9c400-0ec0-11e9-8676-40dfd37fb989.png)

I also don't understand why this offset would be necessary in the first place in OpenGL, or why it would be different between rendering backends. My only guess would be that MonoGame's OpenGL renderer is trying to emulate some old behavior of XNA's original graphics API, as you alluded to.

Perhaps someone that is more familiar with these MonoGame/XNA quirks can chime in with the correct way to handle this inconsistency. As of now it seems like we need to apply the offset when OpenGL is used, and skip it otherwise -- I'm not sure how to detect that via the API.

**Comment by roy-t** [comment]
I'm not sure either how to detect the rendering back-end. The goal of Monogame is that you shouldn't have to :-). I know my way around Monogame (and its community). I'll try look at the Monogame source code this weekend and will report back here once I know more :).

**Comment by roy-t** [comment]
I've checked the MonoGame source code and chatted with a few people. It seems a bug in MonoGame: https://github.com/MonoGame/MonoGame/issues/6619.

**Comment by se5a** [comment]
Anything other than proggyclean font looks fuzzy to me, is this related? it looks fairly similar amount of "fuzzy". using sdl2/opengl

**Comment by sldemai** [comment]
It looks like this behavior was changed in MonoGame release 3.8, which came out a month or so ago.  They removed the 0.5 offset hack in their DesktopGL renderer.  With MonoGame 3.8 DesktopGL, the current ImGui.NET XNA sample renderer draws fuzzy, and it is fixed by setting the offset back to 0.  

There is a flag on the GraphicsDevice object called UseHalfPixelOffset that can be used to detect this behavior in MonoGame (currently only supported in DesktopGL).
